### PR TITLE
Export DividerWidget and document its purpose

### LINKED ISSUE #40: Consider exposing DividerWidget
I'm using MultiSplitView with a theme with one of the stock DividerPainter. However, I want to wrap the actual divider area widget with a tooltip widget. This could easily be accomplished by using the `dividerBuilder` property. Internally, if no custom dividerBuilder is set, it uses the `DividerWidget` and passes along the parameters from the function parameters of the dividerBuilder function, which will then use the painter in the theme to paint the divider based on its state. I want to continue using the painter framework (very convenient) but wrap the DividerWidget with a widget that will display a tooltip on hover. Right now DividerWidget is marked as internal so it's not exported.

### PR DESCRIPTION
**Pull request by klondikedragon**
Hi @caduandrade see what you think, this could close #40. This mod allowed me to easily add a tooltip for the divider while still using the theme divider painter.

This package is brilliant thank you for contributing this to the community!

### CODE REVIEW

**Comment by caduandrade** [comment]
Hi @klondikedragon!

Thank you for your help!

I was thinking of something more direct to the developer. Maybe the developer doesn't need to know which is the default divider class. I believe that changing the `DividerBuilder` by adding the default divider could be enough. So the developer could wrap it or ignore returning a new `Widget`.

Something like this:

```dart
typedef DividerBuilder = Widget Function(Axis axis, int index, bool resizable,
    bool dragging, bool highlighted, MultiSplitViewThemeData themeData, Widget divider);
```

**Comment by klondikedragon** [comment]
@caduandrade that approach could work too. if the `DividerBuilder` signature was changed to accept the default divider, then it would always do the work required to build the create the DividerWidget object even if that was thrown away. That's not really a big deal because it's not actually building the widget itself if the widget isn't put into the widget tree (the constructor is just setting a few fields), so maybe it's just a pedantic concern.

Another option to consider would be for the package to expose a default divider builder that would build the default DividerWidget, but without exposing the DividerWidget directly. Something like:

```dart
class MultiSplitView extends StatefulWidget {
  static Widget defaultDividerBuilder(Axis axis, int index, bool resizable,
    bool dragging, bool highlighted, MultiSplitViewThemeData themeData) =>
      DividerWidget(
        axis: axis,
        index: index,
        themeData: themeData,
        highlighted: highlighted,
        resizable: widget.resizable,
        dragging: dragging);
```
Then my code could create a custom DividerBuilder that could call the defaultDividerBuilder to construct the default widget, and wrap it, etc.

What do you think? I'd be totally happy by your proposal above as it's a little more convenient to use for my use case, but it breaks backwards compatibility. I'd be happy to update the PR with whichever direction you'd prefer.

**Comment by caduandrade** [comment]
Hi @klondikedragon! 

I'm so sorry, you can ignore my idea. I realized that the `DividerWidget` has only the visual effect (painting). All events like click and drag are created by `MultiSplitView`. So it's harmless to export it.

**Review by caduandrade — APPROVED** [review]

**Comment by caduandrade** [comment]
It's late here. Tomorrow I will update the CHANGELOG and maybe create an example in the README. Then release the version ok?

Thanks a lot for your contribution. Anything else just let me know.

**Comment by klondikedragon** [comment]
@caduandrade -- thank you!!

**Pull request merged**
