### PR TITLE
Made AreaId encodable and sortable

### PR DESCRIPTION
**Pull request by stan-at-work**
This PR fixes [this](https://github.com/caduandrade/multi_split_view/issues/94) issue.

### CODE REVIEW

**Comment by stan-at-work** [comment]
Any updates on this ?

**Comment by caduandrade** [comment]
Hi @stan-at-work!

A few points:

1) I think `_AreaId` should not receive an `id`, because if there is an `id`, `_AreaId` would not even be instantiated. This class represents an automatically generated or undefined `id`. Perhaps the name could be `_AreaUndefinedId`.

2) This change does not make `Area` encodable, only `_AreaId`. Right?  I believe the `Area` will not be possible to do it automatically because it receives functions as parameters. In this case, perhaps the solution is to have a (static?) registry to map functions with some identifier. The `toJson` method could replace the function with its identifier. The `fromJson` method could obtain the correct function from the registry given the identifier. Anyone using the API could map their functions to this registry.

What do you think? Does that make sense?

**Comment by stan-at-work** [comment]
Hey ✋

1: Yes and no... I like to give people the freedom to pass their own parameters to objects if possible.  
    I think it does no harm if you can pass them in. This way, we give others the freedom and are not limited to one implementation.

2: Correct, this only makes `_AreaId` encodable, not `Area`.  
    You can manually make `Area` encodable, so that's not necessary.

**Comment by stan-at-work** [comment]
@caduandrade Hello ?

**Comment by stan-at-work** [comment]
@caduandrade Could you look at this ?

**Comment by stan-at-work** [comment]
?

**Comment by caduandrade** [comment]
Hi! I'm sorry for not getting back to you sooner. I'm canceling because these changes do not solve the problem since the Area can have dynamic functions and objects. For cases where a fixed conversion is not possible, the API itself suggests using `jsonEncode` with the `toEncodable` parameter. Sorting can also be used with a comparison function.

**Comment by stan-at-work** [comment]
I don't understand. This fixes a bug and brings no problems to the existing code?

And the dynamic functions have nothing to do with this?

**Comment by stan-at-work** [comment]
Its necessary if you want to save an Area and because currently _AreaId can't be encodes using jsonEncode this is required. This is a basic feature that for some stupid reason is not build in to dart.

**Comment by caduandrade** [comment]
There is no problem with Dart. No language could solve this automatically. This is not a bug as well, it is expected.

The code you suggested solves your problem but is not a solution for the API/package that has a more generic use. It also does not make sense to define an ID in an object that was supposed to have no ID.

The important thing is for you to understand that it is not possible to automatically serialize dynamic and functions. If someone uses an enum as an ID, for example, they would not be able to rebuild the Area with your suggestion.

The simple and correct solution is to use the optional parameter `toEncodable`, as the official documentation suggests. This parameter exists for these cases.

**Pull request closed without merging**
